src/Entity/Donate.php
<?php

namespace App\Entity;

use App\Repository\DonateRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DonateRepository::class)]
class Donate
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_At = null;

    #[ORM\Column(length: 255)]
    private ?string $created_By = null;

    #[ORM\Column]
    private ?int $quantity = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_At;
    }

    public function setCreatedAt(\DateTimeImmutable $created_At): static
    {
        $this->created_At = $created_At;

        return $this;
    }

    public function getCreatedBy(): ?string
    {
        return $this->created_By;
    }

    public function setCreatedBy(string $created_By): static
    {
        $this->created_By = $created_By;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): static
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }
}

src/Form/DonateType.php
<?php

namespace App\Form;

use App\Entity\Donate;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DonateType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('type', TextType::class, [
                'attr' => [
                    'class' => 'isk-h-8 isk-w-full isk-px-3 isk-py-2.5 isk-text-sm isk-rounded-lg'
                ],
                'label_attr' => [
                    'class' => ''
                ]
            ])
            ->add('created_At', DateTimeType::class, [
                'attr' => [
                    'class' => 'isk-h-8 isk-w-full isk-px-3 isk-py-2.5 isk-text-sm isk-rounded-lg'
                ],
                'label_attr' => [
                    'class' => ''
                ]
            ])
            ->add('created_By', TextType::class, [
                'attr' => [
                    'class' => 'isk-h-8 isk-w-full isk-px-3 isk-py-2.5 isk-text-sm isk-rounded-lg'
                ],
                'label_attr' => [
                    'class' => ''
                ]
            ])
            ->add('quantity', IntegerType::class, [
                'attr' => [
                    'class' => 'isk-h-8 isk-w-full isk-px-3 isk-py-2.5 isk-text-sm isk-rounded-lg'
                ],
                'label_attr' => [
                    'class' => ''
                ]
            ])
            ->add('description', TextareaType::class, [
                'attr' => [
                    'class' => 'isk-h-8 isk-w-full isk-px-3 isk-py-2.5 isk-text-sm isk-rounded-lg'
                ],
                'label_attr' => [
                    'class' => ''
                ]
            ])
            ->add('title', TextType::class, [
                'attr' => [
                    'class' => 'isk-h-8 isk-w-full isk-px-3 isk-py-2.5 isk-text-sm isk-rounded-lg'
                ],
                'label_attr' => [
                    'class' => ''
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Donate::class,
        ]);
    }
}

src/Controller/DonateController.php
<?php

namespace App\Controller;

use App\Entity\Donate;
use App\Form\DonateType;
use App\Repository\DonateRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/donate')]
class DonateController extends AbstractController
{
    #[Route('/', name: 'app_donate_index', methods: ['GET'])]
    public function index(DonateRepository $donateRepository): Response
    {
        return $this->render('donate/index.html.twig', [
            'donates' => $donateRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_donate_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $donate = new Donate();
        $form = $this->createForm(DonateType::class, $donate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($donate);
            $entityManager->flush();

            return $this->redirectToRoute('app_donate_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('donate/new.html.twig', [
            'donate' => $donate,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_donate_show', methods: ['GET'])]
    public function show(Donate $donate): Response
    {
        return $this->render('donate/show.html.twig', [
            'donate' => $donate,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_donate_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Donate $donate, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(DonateType::class, $donate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_donate_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('donate/edit.html.twig', [
            'donate' => $donate,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_donate_delete', methods: ['POST'])]
    public function delete(Request $request, Donate $donate, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$donate->getId(), $request->request->get('_token'))) {
            $entityManager->remove($donate);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_donate_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/donate/_delete_form.html.twig
<form method="post" action="{{ path('app_donate_delete', {'id': donate.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ donate.id) }}">
    <button class="btn">Delete</button>
</form>

templates/donate/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/donate/edit.html.twig
{% extends 'baseV1.html.twig' %}

{% block title %}Edit Donate{% endblock %}

{% block body %}
   <div class=" p-9 bg-zinc-200 rounded-xl">
    <div>
        <h1 class="flex justify-center text-3xl font-bold mb-9 text-sky-800">Edit Donate</h1>
        <form class=" max-w-lg items-center border-neutral-950" action="{{ path('app_donate_index') }}" method="post">
            {{ form_start(form) }}
            <div>
                {{ form_label(form.type, 'Type') }}
                {{ form_widget(form.type) }}
            </div>
            <div>
                {{ form_label(form.created_At, 'Created At') }}
                {{ form_widget(form.created_At) }}
            </div>
            <div>
                {{ form_label(form.created_By, 'Created By') }}
                {{ form_widget(form.created_By) }}
            </div>
            <div>
                {{ form_label(form.quantity, 'Quantity') }}
                {{ form_widget(form.quantity) }}
            </div>
            <div>
                {{ form_label(form.description, 'Description') }}
                {{ form_widget(form.description) }}
            </div>
            <div>
                {{ form_label(form.title, 'Title') }}
                {{ form_widget(form.title) }}
            </div>
            <div class="flex justify-between mt-4">
                <div>
                    <button type="submit" class="btn bg-gray-700 hover:bg-blue-700 text-white font-bold py-2 px-2 rounded">Update</button>
                </div>
                <div>
                    <a href="{{ path('app_donate_index') }}" class="btn bg-gray-700 hover:bg-blue-700 text-white font-bold py-2 px-1 rounded mr-4">Back to List</a>
                </div>
                <div>
                    <form method="post" action="{{ path('app_donate_delete', {'id': donate.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ donate.id) }}">
                        <button type="submit" class="btn bg-gray-700 hover:bg-red-700 text-white font-bold py-2 px-2 rounded">Delete</button>
                    </form>
                </div>
            </div>
            {{ form_end(form) }}
        </form>
    </div>
</div>

{% endblock %}

templates/donate/index.html.twig
{% extends 'baseV1.html.twig' %}

{% block title %}Donate Index{% endblock %}

{% block body %}
<div class="container mx-auto p-4">
    <h1 class="text-center font-bold text-4xl mb-8">Donate Index</h1>
      <div class="overflow-x-auto">
        <table class="table-auto shadow-md rounded-lg bg-white w-full">
            <thead class="text-gray-700 bg-gray-200">
                <tr>
                    <th class="py-2 px-4">Id</th>
                    <th class="py-2 px-4">Type</th>
                    <th class="py-2 px-4">Created At</th>
                    <th class="py-2 px-4">Created By</th>
                    <th class="py-2 px-4">Quantity</th>
                    <th class="py-2 px-4">Description</th>
                    <th class="py-2 px-4">Title</th>
                    <th class="py-2 px-4">Actions</th>
                </tr>
            </thead>
            <tbody class="text-gray-600">
                {% for donate in donates %}
                <tr>
                    <td class="py-2 border px-4">{{ donate.id }}</td>
                    <td class="py-2 border px-4">{{ donate.type }}</td>
                    <td class="py-2 border px-4">{{ donate.createdAt ? donate.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                    <td class="py-2 border px-4">{{ donate.createdBy }}</td>
                    <td class="py-2 border px-4">{{ donate.quantity }}</td>
                    <td class="py-2 border px-4">{{ donate.description }}</td>
                    <td class="py-2 border px-4">{{ donate.title }}</td>
                    <td class="py-2 border px-4">
                        <a href="{{ path('app_donate_show', {'id': donate.id}) }}" class="text-blue-500 hover:underline">Show</a>
                        <a href="{{ path('app_donate_edit', {'id': donate.id}) }}" class="text-blue-500 ml-2 hover:underline">Edit</a>
                    </td>
                </tr>
                {% else %}
                <tr>
                    <td colspan="8" class="border text-center py-2 px-4">No records found</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="mt-8 justify-center flex">
        <a href="{{ path('app_donate_new') }}" class="shadow-md rounded-full bg-blue-500 ease-in-out duration-300 transition text-white font-bold py-2 px-6 hover:bg-blue-600">Create New</a>
    </div>
</div>
{% endblock %}

templates/donate/new.html.twig
{% extends 'baseV1.html.twig' %}

{% block title %}New Donate{% endblock %}

{% block body %}
     <div class="p-9 rounded-xl bg-zinc-200">
       <div>
        <h1 class="mb-4 text-3xl font-extrabold text-gray-900 dark:text-white md:text-5xl lg:text-6xl"><span class="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">Create New Donate</span></h1>
             <form class="max-w-md items-center border-neutral-950" action="{{ path('app_donate_index') }}" method="post">
          {{ form_start(form) }}
        <div>
            {{ form_label(form.type, 'Type') }}
            {{ form_widget(form.type) }}
        </div>
        <div>
            {{ form_label(form.created_At, 'Created At') }}
            {{ form_widget(form.created_At) }}
        </div>
        <div>
            {{ form_label(form.created_By, 'Created By') }}
            {{ form_widget(form.created_By) }}
        </div>
        <div>
            {{ form_label(form.quantity, 'Quantity') }}
            {{ form_widget(form.quantity) }}
        </div>
        <div>
            {{ form_label(form.description, 'Description') }}
            {{ form_widget(form.description) }}
        </div>
        <div>
            {{ form_label(form.title, 'Title') }}
            {{ form_widget(form.title) }}
        </div>
        <div class="flex justify-center mt-7">
              <button type="submit" class="relative inline-flex items-center justify-center py-0.9 mb-2 me-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-cyan-500 to-blue-500 group-hover:from-cyan-500 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-cyan-200 dark:focus:ring-cyan-800">
                    <span class="relative px-7 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">Save</span>
                </button> 
            <a href="{{ path('app_donate_index') }}"  class="ml-4 mt-2 text-gray-500 hover:text-sky-700">Back to List</a>    
        </div>
    
        {{ form_end(form) }}
            </form>
        </div>
    </div>
{% endblock %}

templates/donate/show.html.twig
{% extends 'baseV1.html.twig' %}

{% block title %}Donate Index{% endblock %}

{% block body %}
<div class="container">
    <h1>Donate Index</h1>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead class="thead-dark">
                <tr>
                    <th>Id</th>
                    <th>Type</th>
                    <th>Created At</th>
                    <th>Created By</th>
                    <th>Quantity</th>
                    <th>Description</th>
                    <th>Title</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for donate in donates %}
                <tr>
                    <td>{{ donate.id }}</td>
                    <td>{{ donate.type }}</td>
                    <td>{{ donate.createdAt ? donate.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ donate.createdBy }}</td>
                    <td>{{ donate.quantity }}</td>
                    <td>{{ donate.description }}</td>
                    <td>{{ donate.title }}</td>
                    <td>
                        <a href="{{ path('app_donate_show', {'id': donate.id}) }}" class="btn btn-primary">Show</a>
                        <a href="{{ path('app_donate_edit', {'id': donate.id}) }}" class="btn btn-secondary">Edit</a>
                    </td>
                </tr>
                {% else %}
                <tr>
                    <td colspan="8">No records found</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div>
        <a href="{{ path('app_donate_new') }}" class="btn btn-success">Create New</a>
    </div>
</div>
{% endblock %}