src/Entity/Family.php
<?php

namespace App\Entity;

use App\Repository\FamilyRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FamilyRepository::class)]
class Family
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    private ?string $familyName = null;

    #[ORM\Column(length: 255)]
    private ?string $Adress = null;

    #[ORM\Column]
    private ?int $Phone = null;

    #[ORM\Column]
    private ?int $composition = null;

    #[ORM\Column(length: 255)]
    private ?string $Accommodation = null;

    #[ORM\Column(length: 255)]
    private ?string $Father_Profession = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $mother_Profession = null;

    #[ORM\Column(length: 255)]
    private ?string $Insurance = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Health_Status = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFamilyName(): ?string
    {
        return $this->familyName;
    }

    public function setFamilyName(string $familyName): static
    {
        $this->familyName = $familyName;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->Adress;
    }

    public function setAdress(string $Adress): static
    {
        $this->Adress = $Adress;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->Phone;
    }

    public function setPhone(int $Phone): static
    {
        $this->Phone = $Phone;

        return $this;
    }

    public function getComposition(): ?int
    {
        return $this->composition;
    }

    public function setComposition(int $composition): static
    {
        $this->composition = $composition;

        return $this;
    }

    public function getAccommodation(): ?string
    {
        return $this->Accommodation;
    }

    public function setAccommodation(string $Accommodation): static
    {
        $this->Accommodation = $Accommodation;

        return $this;
    }

    public function getFatherProfession(): ?string
    {
        return $this->Father_Profession;
    }

    public function setFatherProfession(string $Father_Profession): static
    {
        $this->Father_Profession = $Father_Profession;

        return $this;
    }

    public function getMotherProfession(): ?string
    {
        return $this->mother_Profession;
    }

    public function setMotherProfession(?string $mother_Profession): static
    {
        $this->mother_Profession = $mother_Profession;

        return $this;
    }

    public function getInsurance(): ?string
    {
        return $this->Insurance;
    }

    public function setInsurance(string $Insurance): static
    {
        $this->Insurance = $Insurance;

        return $this;
    }

    public function getHealthStatus(): ?string
    {
        return $this->Health_Status;
    }

    public function setHealthStatus(?string $Health_Status): static
    {
        $this->Health_Status = $Health_Status;

        return $this;
    }
}

templates/UI/dataTable.html.twig
    <!-- /.card -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">View user management</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>User Id</th>
                        <th>Full Name</th>
                        <th>Email</th>
                        <th>Roles</th>
                        <th>Phone</th>
                        <th>Gender</th>
                        <th>Postal Code</th>
                        <th>Country</th>
                        <th>State</th>
                        <th>Address</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr {% if user.blocked %}style="background-color: #fcd2d2" {% endif %}>
                        <td>{{ user.id }}</td>
                        <td>{{ user.name }}</td>
                        <td>{{ user.email }}</td>
                        <td>{{ user.roles | join(', ') }}</td>
                        <td> {{ user.phone }}</td>
                        <td>{{ user.gender }}</td>
                        <td>{{ user.postalCode }}</td>
                        <td>{{ user.country }}</td>
                        <td>{{ user.state }}</td>
                        <td>{{ user.address }}</td>
                        <td class="dataTable-actions">
{#                            <i class="far fa-edit" onclick="window.location='{{ path('admin_user_edit',{'id':user.id}) }}'"></i>  #}
                            <i class="far fa-folder-open" onclick="window.location='{{ path('admin_user_show',{'id':user.id}) }}'"></i>
                            {% if user.id is not same as(app.user.id)  %}
                                <i class="fa fa-trash-alt" onclick="deleteUser('{{ path('admin_user_delete', {'id': user.id, '_token': csrf_token('delete' ~ user.id)}) }}')"></i>
                                <i class="fa {% if user.blocked %} fa-lock-open {% else %} fa-lock {% endif %}" onclick="blockUser('{{ path('admin_user_block', {'id': user.id, '_token': csrf_token('block' ~ user.id)}) }}')"></i>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

templates/UI/navbar.html.twig
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2"></i> 4 new messages
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li>
    </ul>
</nav>

templates/UI/sidebar.html.twig
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="../../index3.html" class="brand-link">
        <img src="{{ asset('dist/img/mtciLogo.png') }}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">CRT El Alia</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
     <br>
        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
            </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-header">User Management</li>
                <li class="nav-item">
                    <a  class="nav-link">
                        <i class="fa-solid fa-circle-user"></i>
                        <p>
                            User
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="far fa-solid fa-users-rectangle nav-icon-1x"style="margin: 3px;"></i>
                                <p>List of users</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="far fa-solid fa-user-plus nav-icon fa-1x"style="margin: 3px;"></i>
                                <p>Add user</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fa-solid fa-ticket"></i>
                        <p>
                            Tickets
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fa-solid fa-calendar-check"></i>
                        <p>
                            Reservation
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fa-brands fa-dropbox"></i>
                        <p>
                            Shipment
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="far fa-solid fa-boxes-stacked nav-icon fa-1x"style="margin: 3px;"></i>
                                <p> All shipments </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="far fa-solid fa-boxes-packing nav-icon fa-1x"style="margin: 3px;"></i>
                                <p> Active Shipments </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="far fa-solid fa-box-archive nav-icon fa-1x"style="margin: 3px;"></i>
                                <p>Inactive Shipments</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fa-solid fa-address-book"></i>
                        <p>
                            Contact
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fa-solid fa-square-plus"></i>
                        <p>
                            Extras
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="far fa-solid fa-user-lock nav-icon-1x"style="margin: 3px;"></i>
                                <p>
                                    Login & Register v1
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="../examples/login.html" class="nav-link">
                                        <i class="fa-solid fa-arrow-right-to-bracket"></i>
                                        <p>Login v1</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="../examples/register.html" class="nav-link">
                                        <i class="fa-regular fa-square-check"></i>
                                        <p>Register v1</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="../examples/forgot-password.html" class="nav-link">
                                        <i class="fa-solid fa-lock"></i>
                                        <p>Forgot Password v1</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="../examples/recover-password.html" class="nav-link">
                                        <i class="fa-solid fa-arrows-rotate"></i>
                                        <p>Recover Password v1</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="far fa-solid fa-user-lock nav-icon fa-1x"style="margin: 3px;"></i>
                                <p>
                                    Login & Register v2
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="../examples/login-v2.html" class="nav-link">
                                        <i class="fa-solid fa-arrow-right-to-bracket"></i>
                                        <p>Login v2</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="../examples/register-v2.html" class="nav-link">
                                        <i class="fa-regular fa-square-check"></i>
                                        <p>Register v2</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="../examples/forgot-password-v2.html" class="nav-link">
                                        <i class="fa-solid fa-lock"></i>
                                        <p>Forgot Password v2</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="../examples/recover-password-v2.html" class="nav-link">
                                        <i class="fa-solid fa-arrows-rotate"></i>
                                        <p>Recover Password v2</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a href="../examples/lockscreen.html" class="nav-link">
                                <i class="far fa-solid fa-lock-open nav-icon fa-1x"style="margin: 3px;"></i>
                                <p>Lockscreen</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../examples/legacy-user-menu.html" class="nav-link">
                                <i class="far fa-solid fa-sliders nav-icon fa-1x"style="margin: 3px;"></i>
                                <p>Legacy User Menu</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../examples/language-menu.html" class="nav-link">
                                <i class="far fa-solid fa-language nav-icon fa-1x"style="margin: 3px;"></i>
                                <p>Language Menu</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../examples/404.html" class="nav-link">
                                <i class="far fa-solid fa-bug nav-icon fa-1x"style="margin: 3px;"></i>
                                <p>Error 404</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../examples/500.html" class="nav-link">
                                <i class="far fa-solid fa-triangle-exclamation nav-icon"></i>
                                <p>Error 500</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../examples/pace.html" class="nav-link">
                                <i class="far fa-brands fa-squarespace nav-icon fa-1x"style="margin: 3px;"></i>
                                <p>Pace</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../examples/blank.html" class="nav-link">
                                <i class="fa-regular fa-circle nav-icon fa-1x"style="margin: 3px;"></i>
                                <p>Blank Page</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../../starter.html" class="nav-link">
                                <i class="far fa-solid fa-circle nav-icon fa-1x"style="margin: 3px;"></i>
                                <p>Starter Page</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fa-solid fa-folder-tree"></i>
                        <p>
                            Search
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="../search/simple.html" class="nav-link">
                                <i class="far fa-solid fa-magnifying-glass nav-icon fa-1x"style="margin: 3px;"></i>
                                <p>Simple Search</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="../search/enhanced.html" class="nav-link">
                                <i class="far fa-brands fa-searchengin nav-icon fa-1x"style="margin: 3px;"></i>
                                <p>Enhanced</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>